# Import the librairies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset

In [5]:
data = pd.read_csv("../data/ai_job_dataset.csv")
data.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

# Exploring the dataset

## NUll Values

In [9]:
display(data.info())

display(data.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

None

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

We don't have null or nan values

## describe

In [10]:
display(data.describe())

,salary_usd,remote_ratio,years_experience,job_description_length,benefits_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,115348.965133,49.483333,6.253200,1503.314733,7.504273
std,60260.940438,40.812712,5.545768,576.127083,1.450870
min,32519.000000,0.000000,0.000000,500.000000,5.000000
25%,70179.750000,0.000000,2.000000,1003.750000,6.200000
50%,99705.000000,50.000000,5.000000,1512.000000,7.500000
75%,146408.500000,100.000000,10.000000,2000.000000,8.800000
max,399095.000000,100.000000,19.000000,2499.000000,10.000000

## The columns

In [21]:
numerical_columns =data.select_dtypes(include=['number'])
categroical_columns = data.select_dtypes(include=['object'])
print("**"*100)
print("les colonnes numeriques :")
print("**"*100)
display(numerical_columns.columns)
print(len(numerical_columns.columns))
print("**"*100)
print("les colonnes categoriels")
print("**"*100)
display(categroical_columns.columns)
print(len(categroical_columns.columns))

********************************************************************************************************************************************************************************************************
les colonnes numeriques :
********************************************************************************************************************************************************************************************************

Index(['salary_usd', 'remote_ratio', 'years_experience',
       'job_description_length', 'benefits_score'],
      dtype='object')

5
********************************************************************************************************************************************************************************************************
les colonnes categoriels
********************************************************************************************************************************************************************************************************

Index(['job_id', 'job_title', 'salary_currency', 'experience_level',
       'employment_type', 'company_location', 'company_size',
       'employee_residence', 'required_skills', 'education_required',
       'industry', 'posting_date', 'application_deadline', 'company_name'],
      dtype='object')

14

In [24]:
for col in categroical_columns.columns :
    print("*"*100)
    print(col)
    display(data[col].unique())

****************************************************************************************************
job_id

array(['AI00001', 'AI00002', 'AI00003', ..., 'AI14998', 'AI14999',
       'AI15000'], shape=(15000,), dtype=object)

****************************************************************************************************
job_title

array(['AI Research Scientist', 'AI Software Engineer', 'AI Specialist',
       'NLP Engineer', 'AI Consultant', 'AI Architect',
       'Principal Data Scientist', 'Data Analyst',
       'Autonomous Systems Engineer', 'AI Product Manager',
       'Machine Learning Engineer', 'Data Engineer', 'Research Scientist',
       'ML Ops Engineer', 'Robotics Engineer', 'Head of AI',
       'Deep Learning Engineer', 'Data Scientist',
       'Machine Learning Researcher', 'Computer Vision Engineer'],
      dtype=object)

****************************************************************************************************
salary_currency

array(['USD', 'EUR', 'GBP'], dtype=object)

****************************************************************************************************
experience_level

array(['SE', 'EN', 'MI', 'EX'], dtype=object)

****************************************************************************************************
employment_type

array(['CT', 'FL', 'PT', 'FT'], dtype=object)

****************************************************************************************************
company_location

array(['China', 'Canada', 'Switzerland', 'India', 'France', 'Germany',
       'United Kingdom', 'Singapore', 'Austria', 'Sweden', 'South Korea',
       'Norway', 'Netherlands', 'United States', 'Israel', 'Australia',
       'Ireland', 'Denmark', 'Finland', 'Japan'], dtype=object)

****************************************************************************************************
company_size

array(['M', 'L', 'S'], dtype=object)

****************************************************************************************************
employee_residence

array(['China', 'Ireland', 'South Korea', 'India', 'Singapore', 'Germany',
       'United Kingdom', 'France', 'Austria', 'Sweden', 'Norway',
       'Israel', 'United States', 'Netherlands', 'Denmark', 'Switzerland',
       'Finland', 'Japan', 'Canada', 'Australia'], dtype=object)

****************************************************************************************************
required_skills

array(['Tableau, PyTorch, Kubernetes, Linux, NLP',
       'Deep Learning, AWS, Mathematics, Python, Docker',
       'Kubernetes, Deep Learning, Java, Hadoop, NLP', ...,
       'Scala, Spark, NLP', 'Java, Computer Vision, Python, TensorFlow',
       'Scala, Azure, Deep Learning, GCP, Mathematics'],
      shape=(13663,), dtype=object)

****************************************************************************************************
education_required

array(['Bachelor', 'Master', 'Associate', 'PhD'], dtype=object)

****************************************************************************************************
industry

array(['Automotive', 'Media', 'Education', 'Consulting', 'Healthcare',
       'Gaming', 'Government', 'Telecommunications', 'Manufacturing',
       'Energy', 'Technology', 'Real Estate', 'Finance', 'Transportation',
       'Retail'], dtype=object)

****************************************************************************************************
posting_date

array(['2024-10-18', '2024-11-20', '2025-03-18', '2024-12-23',
       '2025-04-15', '2024-08-31', '2024-12-29', '2024-06-07',
       '2024-11-04', '2024-10-20', '2025-01-29', '2024-07-16',
       '2024-02-11', '2024-10-02', '2024-09-28', '2025-02-06',
       '2024-04-24', '2024-04-30', '2024-05-01', '2024-06-21',
       '2024-04-23', '2025-03-13', '2024-10-27', '2024-08-01',
       '2024-11-18', '2025-01-10', '2024-10-08', '2024-01-18',
       '2024-05-16', '2024-01-31', '2024-08-28', '2024-03-01',
       '2024-10-26', '2024-10-17', '2024-01-14', '2024-06-15',
       '2024-02-24', '2025-03-17', '2025-02-01', '2025-03-03',
       '2024-01-10', '2024-11-16', '2024-09-05', '2024-08-08',
       '2025-03-10', '2024-08-16', '2024-03-12', '2024-07-07',
       '2024-08-05', '2024-07-29', '2025-03-22', '2024-02-09',
       '2024-03-20', '2024-06-22', '2024-06-05', '2024-03-23',
       '2024-02-20', '2024-12-15', '2024-09-01', '2025-02-09',
       '2024-08-30', '2024-10-31', '2024-02-14', '2024-05-31',
       '2024-08-02', '2024-11-29', '2025-04-08', '2024-09-19',
       '2024-06-10', '2024-04-20', '2025-02-13', '2024-04-01',
       '2024-02-05', '2024-06-20', '2024-06-19', '2024-07-14',
       '2025-04-16', '2025-02-15', '2024-05-20', '2024-11-19',
       '2025-04-26', '2024-07-10', '2024-04-10', '2025-04-05',
       '2024-12-04', '2025-01-12', '2025-01-02', '2024-01-25',
       '2024-01-27', '2024-07-21', '2024-09-15', '2024-01-28',
       '2024-12-13', '2024-09-04', '2024-03-08', '2024-05-13',
       '2024-03-18', '2024-03-13', '2024-08-14', '2024-06-04',
       '2024-08-11', '2024-10-22', '2024-04-15', '2024-05-18',
       '2025-01-06', '2025-03-26', '2025-04-19', '2024-12-25',
       '2024-08-24', '2024-08-03', '2025-03-02', '2024-03-28',
       '2025-02-03', '2025-01-16', '2024-08-09', '2024-11-06',
       '2025-01-05', '2024-05-24', '2025-04-12', '2024-09-23',
       '2024-03-09', '2024-11-17', '2024-05-22', '2024-12-02',
       '2024-03-30', '2024-07-04', '2024-10-25', '2024-04-21',
       '2024-05-23', '2024-01-12', '2024-03-19', '2025-03-04',
       '2024-12-12', '2024-03-14', '2024-06-25', '2024-10-05',
       '2025-01-30', '2024-07-19', '2024-01-06', '2024-08-25',
       '2025-03-15', '2025-01-08', '2024-11-09', '2024-11-01',
       '2024-07-11', '2024-03-10', '2024-09-20', '2025-01-28',
       '2024-10-07', '2024-06-01', '2024-02-06', '2024-09-30',
       '2024-12-20', '2024-10-15', '2024-02-01', '2024-08-07',
       '2024-07-17', '2025-02-17', '2025-02-07', '2024-02-25',
       '2024-08-23', '2025-03-29', '2025-03-20', '2024-06-14',
       '2024-11-22', '2024-11-26', '2024-03-29', '2024-09-14',
       '2025-03-19', '2024-01-30', '2024-07-15', '2024-09-08',
       '2025-01-25', '2024-02-07', '2025-04-20', '2025-02-08',
       '2024-04-18', '2025-01-15', '2025-03-30', '2024-10-11',
       '2025-02-04', '2024-03-22', '2024-07-03', '2025-04-27',
       '2024-12-16', '2024-07-01', '2024-02-19', '2025-02-11',
       '2025-03-06', '2024-12-09', '2025-02-02', '2024-04-12',
       '2024-09-13', '2024-10-10', '2024-01-20', '2024-05-05',
       '2024-12-14', '2024-05-06', '2024-01-21', '2024-08-20',
       '2024-12-07', '2024-12-21', '2024-03-11', '2025-01-27',
       '2024-06-06', '2024-12-17', '2025-04-03', '2025-03-21',
       '2024-06-26', '2025-04-18', '2025-03-08', '2024-06-27',
       '2024-04-28', '2024-04-27', '2024-08-22', '2024-02-16',
       '2024-10-09', '2024-05-17', '2025-01-19', '2024-02-23',
       '2025-04-30', '2024-02-22', '2025-04-23', '2025-03-14',
       '2024-03-24', '2025-04-11', '2025-02-18', '2024-01-22',
       '2024-03-26', '2025-04-07', '2025-04-04', '2024-05-02',
       '2025-02-26', '2024-07-27', '2024-10-19', '2024-08-19',
       '2024-01-04', '2025-01-18', '2024-07-31', '2025-04-06',
       '2024-08-12', '2024-10-06', '2024-08-13', '2024-06-23',
       '2024-01-08', '2024-07-28', '2024-01-15', '2024-04-14',
       '2024-01-29', '2024-06-02', '2025-04-01', '2024-03-31',
       '2024-07-06', '2025-04-09', '2024-04-04', '2024-12-26',
       '2024-08-21', '2024-01-13', '2025-03-07', '2024-05-21',
       '2024-05-15', '2025-04-25', '2024-08-15', '2024-06-17',
       '2024-05-07', '2024-04-22', '2025-04-21', '2024-02-13',
       '2024-10-12', '2025-03-09', '2025-01-26', '2024-05-11',
       '2025-01-31', '2025-04-10', '2024-10-04', '2024-11-02',
       '2024-09-02', '2024-11-27', '2025-03-27', '2024-11-13',
       '2024-01-09', '2024-06-12', '2024-02-18', '2024-11-11',
       '2024-12-10', '2024-08-06', '2024-04-08', '2024-05-14',
       '2024-12-22', '2024-07-25', '2024-01-11', '2025-03-31',
       '2024-07-05', '2024-02-28', '2024-11-07', '2024-09-09',
       '2024-09-17', '2024-05-09', '2024-11-24', '2025-04-17',
       '2024-09-12', '2025-04-14', '2025-01-04', '2024-06-08',
       '2024-02-29', '2025-02-27', '2024-01-03', '2025-04-29',
       '2025-02-28', '2024-05-26', '2024-08-10', '2024-07-26',
       '2024-07-13', '2025-02-12', '2024-06-16', '2025-01-13',
       '2024-10-16', '2024-02-08', '2024-01-17', '2024-04-25',
       '2024-11-14', '2024-07-30', '2024-10-21', '2024-05-04',
       '2024-12-05', '2024-09-16', '2024-07-08', '2024-06-11',
       '2024-12-31', '2024-02-02', '2024-03-04', '2024-05-03',
       '2024-05-12', '2024-03-05', '2024-02-10', '2025-02-19',
       '2024-05-30', '2024-11-23', '2024-03-03', '2024-09-07',
       '2024-08-17', '2025-04-24', '2024-05-25', '2024-10-23',
       '2024-10-14', '2025-02-24', '2024-03-21', '2024-12-28',
       '2024-04-07', '2024-07-18', '2024-04-29', '2024-12-24',
       '2024-04-06', '2024-11-21', '2024-01-05', '2024-11-15',
       '2025-02-23', '2024-06-29', '2024-04-09', '2024-09-18',
       '2024-12-08', '2024-09-10', '2024-06-09', '2025-04-02',
       '2024-03-06', '2024-06-03', '2024-06-13', '2025-03-28',
       '2024-11-25', '2024-07-12', '2024-08-26', '2025-02-14',
       '2024-12-18', '2024-02-12', '2024-07-20', '2024-12-19',
       '2025-01-24', '2024-10-29', '2025-03-11', '2024-11-28',
       '2024-04-19', '2025-03-05', '2025-01-01', '2024-02-17',
       '2025-02-10', '2024-02-26', '2024-08-04', '2024-01-07',
       '2024-09-27', '2025-02-25', '2025-01-22', '2024-07-23',
       '2025-01-03', '2024-06-30', '2024-03-27', '2025-01-07',
       '2024-09-24', '2025-04-22', '2024-09-06', '2024-11-10',
       '2025-03-24', '2025-01-17', '2024-11-03', '2025-04-28',
       '2024-02-27', '2025-03-23', '2024-04-05', '2025-01-14',
       '2024-05-08', '2025-03-01', '2024-02-21', '2024-06-24',
       '2025-03-16', '2025-04-13', '2024-11-08', '2024-09-21',
       '2024-11-30', '2025-02-21', '2024-07-02', '2024-01-19',
       '2024-12-01', '2024-12-11', '2025-01-23', '2025-02-05',
       '2025-01-21', '2024-01-24', '2025-02-20', '2024-05-28',
       '2024-02-15', '2024-09-03', '2024-10-30', '2024-04-16',
       '2024-03-16', '2024-06-28', '2024-06-18', '2024-05-29',
       '2024-02-04', '2024-08-27', '2024-10-24', '2024-04-11',
       '2024-07-22', '2024-09-22', '2024-09-29', '2025-01-11',
       '2024-02-03', '2024-10-01', '2024-08-29', '2024-03-07',
       '2024-04-26', '2024-04-02', '2025-01-09', '2024-05-19',
       '2024-10-13', '2024-03-02', '2024-12-03', '2024-04-03',
       '2024-12-27', '2024-05-10', '2025-02-22', '2024-03-17',
       '2024-01-26', '2024-08-18', '2024-04-17', '2024-05-27',
       '2024-09-26', '2024-04-13', '2025-03-25', '2024-12-30',
       '2024-03-15', '2024-01-01', '2024-07-24', '2024-10-03',
       '2025-01-20', '2024-01-02', '2025-03-12', '2024-11-05',
       '2024-10-28', '2025-02-16', '2024-09-11', '2024-01-16',
       '2024-07-09', '2024-09-25', '2024-03-25', '2024-11-12',
       '2024-01-23', '2024-12-06'], dtype=object)

****************************************************************************************************
application_deadline

array(['2024-11-07', '2025-01-11', '2025-04-07', '2025-02-24',
       '2025-06-23', '2024-10-04', '2025-02-28', '2024-07-01',
       '2024-11-24', '2024-11-06', '2025-03-05', '2024-08-19',
       '2025-01-27', '2024-02-25', '2024-11-26', '2024-10-26',
       '2025-03-26', '2024-06-03', '2024-05-29', '2024-07-02',
       '2024-08-28', '2024-06-23', '2025-05-11', '2024-06-24',
       '2024-11-18', '2024-10-02', '2025-01-18', '2025-02-20',
       '2024-11-20', '2024-07-26', '2024-03-08', '2024-09-20',
       '2024-03-19', '2024-12-25', '2024-02-26', '2024-11-12',
       '2024-03-12', '2024-07-29', '2024-05-01', '2024-03-09',
       '2025-04-16', '2025-04-11', '2024-06-12', '2025-05-03',
       '2024-03-22', '2024-12-18', '2024-10-25', '2024-09-23',
       '2025-05-17', '2024-10-19', '2024-04-14', '2024-05-02',
       '2024-09-09', '2024-08-26', '2024-09-27', '2025-05-01',
       '2024-03-06', '2024-05-05', '2024-08-14', '2024-03-15',
       '2025-02-11', '2025-02-12', '2024-10-29', '2025-02-23',
       '2024-09-15', '2024-12-15', '2024-04-02', '2024-06-19',
       '2024-10-01', '2025-01-09', '2025-05-13', '2025-01-25',
       '2024-10-06', '2024-08-13', '2024-06-08', '2025-03-10',
       '2024-04-16', '2024-03-11', '2024-08-12', '2024-08-22',
       '2024-09-08', '2025-06-15', '2025-04-15', '2024-07-14',
       '2024-12-07', '2025-05-14', '2024-07-16', '2024-05-08',
       '2024-05-03', '2025-06-13', '2025-01-03', '2025-03-07',
       '2024-06-22', '2025-03-11', '2024-04-04', '2024-02-28',
       '2025-04-03', '2024-03-17', '2024-04-20', '2024-10-10',
       '2024-05-13', '2024-06-25', '2024-05-10', '2024-09-06',
       '2025-02-01', '2025-04-13', '2024-08-25', '2025-01-24',
       '2024-12-02', '2025-04-12', '2024-10-15', '2025-03-30',
       '2025-02-15', '2024-09-16', '2025-01-15', '2024-09-12',
       '2025-02-13', '2024-10-30', '2024-04-07', '2024-12-26',
       '2024-07-27', '2024-04-15', '2024-08-11', '2024-12-11',
       '2024-05-24', '2024-07-09', '2024-12-24', '2024-02-12',
       '2024-07-31', '2024-04-05', '2025-03-24', '2024-07-22',
       '2024-04-21', '2024-08-23', '2024-09-04', '2025-03-27',
       '2024-09-28', '2024-08-31', '2025-01-01', '2025-04-14',
       '2025-02-03', '2024-12-23', '2024-11-23', '2024-08-02',
       '2024-10-23', '2025-02-21', '2024-12-06', '2024-07-15',
       '2025-01-02', '2024-08-01', '2024-03-14', '2024-07-07',
       '2024-07-20', '2024-03-25', '2024-09-24', '2024-09-11',
       '2025-03-16', '2025-05-19', '2025-02-27', '2024-11-13',
       '2025-03-06', '2024-03-31', '2024-10-18', '2025-05-31',
       '2025-05-08', '2024-07-05', '2024-12-20', '2025-01-20',
       '2024-12-09', '2025-04-29', '2024-05-25', '2024-09-30',
       '2024-02-29', '2025-05-30', '2024-05-27', '2024-08-16',
       '2025-02-22', '2024-03-23', '2025-05-24', '2024-03-03',
       '2024-03-26', '2024-05-18', '2024-11-14', '2024-12-12',
       '2024-04-13', '2025-06-09', '2025-05-28', '2025-01-08',
       '2024-08-30', '2024-10-16', '2025-03-23', '2025-05-09',
       '2025-02-08', '2025-01-14', '2024-12-05', '2025-01-13',
       '2024-12-17', '2024-10-11', '2024-02-21', '2025-05-12',
       '2024-12-31', '2024-06-21', '2024-02-24', '2025-02-05',
       '2025-04-17', '2025-02-26', '2024-06-17', '2024-12-19',
       '2024-07-21', '2025-01-30', '2024-10-27', '2025-05-22',
       '2025-05-18', '2024-08-04', '2025-04-30', '2025-06-20',
       '2024-09-05', '2024-11-28', '2025-05-21', '2024-07-17',
       '2024-06-28', '2024-09-21', '2025-05-26', '2024-06-04',
       '2025-03-25', '2024-05-28', '2025-04-24', '2024-05-21',
       '2025-06-07', '2024-04-22', '2024-02-05', '2024-05-19',
       '2025-05-20', '2025-02-19', '2024-05-22', '2024-07-13',
       '2025-04-21', '2025-01-17', '2024-11-29', '2024-09-17',
       '2024-09-26', '2025-05-06', '2024-10-07', '2025-01-29',
       '2024-10-22', '2024-08-17', '2025-05-10', '2024-08-15',
       '2025-02-17', '2024-08-18', '2024-01-31', '2024-02-23',
       '2025-02-09', '2024-03-13', '2024-05-15', '2025-04-28',
       '2024-05-04', '2024-12-13', '2024-06-06', '2024-05-09',
       '2025-05-05', '2024-01-28', '2025-04-01', '2024-06-26',
       '2025-03-14', '2024-07-19', '2024-02-22', '2024-05-17',
       '2025-06-28', '2024-09-13', '2024-07-18', '2025-06-27',
       '2024-03-05', '2024-09-18', '2025-04-26', '2024-09-07',
       '2024-07-23', '2025-04-02', '2024-06-11', '2024-11-30',
       '2024-09-03', '2025-01-07', '2024-12-21', '2024-02-18',
       '2024-07-10', '2024-12-03', '2024-04-30', '2024-02-19',
       '2025-01-12', '2025-03-09', '2024-05-31', '2024-07-24',
       '2024-08-29', '2025-02-02', '2024-08-20', '2025-04-23',
       '2024-02-01', '2024-04-23', '2025-01-10', '2024-10-21',
       '2024-10-28', '2024-06-29', '2024-05-06', '2024-11-22',
       '2024-07-12', '2024-02-20', '2025-04-22', '2024-05-26',
       '2025-04-05', '2024-02-04', '2025-05-27', '2024-08-07',
       '2025-02-18', '2024-09-02', '2025-05-07', '2025-03-04',
       '2024-09-19', '2025-06-24', '2024-12-29', '2025-01-31',
       '2024-10-20', '2024-07-06', '2025-03-02', '2024-11-05',
       '2024-03-20', '2025-04-20', '2024-12-28', '2024-07-03',
       '2025-02-06', '2025-03-31', '2024-11-01', '2024-07-28',
       '2024-11-10', '2024-04-11', '2024-09-10', '2024-05-16',
       '2024-06-09', '2025-06-14', '2024-06-07', '2024-02-15',
       '2024-04-24', '2025-01-19', '2024-04-03', '2024-11-04',
       '2025-06-12', '2024-11-16', '2024-06-16', '2025-03-28',
       '2024-03-16', '2024-05-12', '2024-11-17', '2024-10-09',
       '2024-06-30', '2025-03-21', '2024-03-18', '2024-03-10',
       '2025-06-04', '2024-05-20', '2024-08-05', '2025-01-22',
       '2024-12-10', '2025-02-10', '2024-04-06', '2024-11-11',
       '2024-04-25', '2024-08-08', '2024-12-16', '2024-12-04',
       '2025-07-02', '2024-05-30', '2025-03-03', '2025-05-04',
       '2024-04-29', '2024-12-01', '2024-10-31', '2024-12-30',
       '2025-06-10', '2025-05-02', '2024-10-08', '2024-06-15',
       '2025-02-07', '2025-01-23', '2024-02-13', '2024-02-08',
       '2025-01-21', '2025-01-26', '2025-05-16', '2025-03-12',
       '2025-03-01', '2024-10-05', '2025-04-25', '2024-10-14',
       '2024-06-20', '2025-03-19', '2024-04-26', '2024-07-25',
       '2025-03-18', '2025-01-06', '2024-06-01', '2024-08-21',
       '2024-10-17', '2024-04-27', '2024-10-13', '2024-05-14',
       '2024-02-11', '2025-03-15', '2024-01-17', '2024-04-17',
       '2025-06-11', '2024-08-06', '2024-08-03', '2024-08-27',
       '2025-06-19', '2024-06-13', '2024-11-02', '2024-04-01',
       '2024-10-03', '2024-10-12', '2024-03-30', '2025-03-17',
       '2024-09-22', '2024-03-27', '2024-09-14', '2024-11-08',
       '2024-01-26', '2024-07-08', '2024-02-27', '2024-09-01',
       '2025-04-08', '2024-03-24', '2025-05-15', '2024-05-11',
       '2024-12-22', '2024-02-17', '2025-04-04', '2025-02-25',
       '2025-01-05', '2024-11-15', '2024-06-02', '2024-02-10',
       '2024-11-25', '2024-03-07', '2025-06-03', '2024-08-09',
       '2024-03-01', '2025-06-22', '2024-06-27', '2024-11-09',
       '2024-07-04', '2025-01-04', '2024-12-08', '2025-01-28',
       '2024-04-28', '2024-02-03', '2024-05-07', '2025-03-08',
       '2024-11-27', '2024-06-14', '2025-07-05', '2024-03-04',
       '2025-03-13', '2024-06-10', '2025-06-01', '2024-09-25',
       '2025-04-06', '2025-04-27', '2024-04-08', '2024-07-30',
       '2025-04-18', '2024-04-18', '2024-05-23', '2025-05-29',
       '2024-09-29', '2025-06-30', '2024-04-12', '2024-08-10',
       '2024-04-19', '2025-01-16', '2025-07-01', '2024-01-25',
       '2025-04-10', '2025-04-19', '2024-11-19', '2025-03-20',
       '2025-03-29', '2024-03-29', '2024-04-10', '2024-02-16',
       '2024-02-07', '2024-06-05', '2025-05-25', '2024-01-23',
       '2024-08-24', '2024-03-21', '2024-04-09', '2025-02-16',
       '2024-02-06', '2025-03-22', '2024-11-21', '2024-11-03',
       '2025-05-23', '2024-12-27', '2024-02-14', '2024-01-24',
       '2024-06-18', '2025-06-08', '2024-01-22', '2024-02-09',
       '2025-06-17', '2024-03-02', '2025-06-02', '2025-06-21',
       '2024-01-30', '2025-06-25', '2024-07-11', '2024-01-21',
       '2024-12-14', '2025-06-26', '2025-02-04', '2025-06-16',
       '2024-01-29', '2025-04-09', '2024-03-28', '2025-06-05',
       '2024-01-19', '2024-10-24', '2024-01-20', '2025-02-14',
       '2025-07-03', '2025-06-06', '2025-07-06', '2025-07-04',
       '2025-06-18', '2025-07-09', '2024-02-02', '2024-01-27',
       '2025-06-29', '2025-07-10', '2025-07-08', '2024-01-18',
       '2025-07-11', '2024-01-16', '2025-07-07'], dtype=object)

****************************************************************************************************
company_name

array(['Smart Analytics', 'TechCorp Inc', 'Autonomous Tech',
       'Future Systems', 'Advanced Robotics', 'Neural Networks Co',
       'DataVision Ltd', 'Cloud AI Solutions', 'Quantum Computing Inc',
       'Predictive Systems', 'AI Innovations', 'Algorithmic Solutions',
       'Cognitive Computing', 'DeepTech Ventures',
       'Machine Intelligence Group', 'Digital Transformation LLC'],
      dtype=object)

In [25]:
for col in numerical_columns.columns :
    print("*"*100)
    print(col)
    display(data[col].unique())

****************************************************************************************************
salary_usd

array([ 90376,  61895, 152626, ..., 189490,  79461,  56481],
      shape=(14315,))

****************************************************************************************************
remote_ratio

array([ 50, 100,   0])

****************************************************************************************************
years_experience

array([ 9,  1,  2,  7,  0,  3,  5,  8, 15,  6,  4, 16, 10, 18, 12, 19, 17,
       13, 11, 14])

****************************************************************************************************
job_description_length

array([1076, 1268, 1974, ...,  604, 1975,  723], shape=(2000,))

****************************************************************************************************
benefits_score

array([ 5.9,  5.2,  9.4,  8.6,  6.6,  6.3,  7.6,  9.3,  5.8,  9.9,  6.8,
        9.1,  9.8,  9.6,  8.7,  6.7, 10. ,  6.9,  7.4,  8.8,  7.7,  6. ,
        9.2,  5.3,  5.7,  7.9,  6.1,  8.1,  8. ,  5.1,  7.5,  5.5,  5.4,
        9.7,  7.2,  5.6,  9. ,  6.2,  6.5,  7.1,  9.5,  7. ,  8.2,  8.4,
        7.8,  6.4,  8.3,  8.9,  7.3,  8.5,  5. ])